const SHOPTYPE={
  UPDATE_DATA:'UPDATE_DATA',
  FETCH_COLLECTION_START:' FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCSESS:'FETCH_COLLECTION_SUCCSESS',
  FEATCH_COLLECTION_FAILUR:'FEATCH_COLLECTION_FAILUR'
}

export default SHOPTYPE